#!/bin/bash

echo "source the env"
module load python
export CC=/home/rb7e15/gcc/bin/gcc
export LD_LIBRARY_PATH=/home/rb7e15/gcc/lib64:$LD_LIBRARY_PATH
source /home/rb7e15/2.7v/TFenv/bin/activate

echo  "launch the command"
python /home/rb7e15/2.7v/model.py --total_num_epochs=3000 --state_size=200 --test_ratio=0.33 --num_samples=1500 --batch_size=100 --learning_rate=0.005 --epsilon=0.001 --max_output_ops=5 --num_features=4 --train_fn=np_center --model=RLRNN --state_fn=relu --pen_sofmax=False --augument_grad=False --max_reward=1000 --relaunch=True --seed=42718 --name=total_num_epochs#3000~state_size#200~test_ratio#0.33~num_samples#1500~batch_size#100~learning_rate#0.005~epsilon#0.001~num_features#4~state_fn#relu~pen_sofmax#False~augument_grad#False~max_reward#1000~relaunch#True~seed#42718
